# Generated by Django 2.1.1 on 2018-10-15 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='my_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUser'),
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
