# Generated by Django 2.1.1 on 2018-10-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181023_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='my_user',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
