# Generated by Django 2.1.1 on 2018-10-25 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPoolPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='driver_interface.Post')),
            ],
            bases=('driver_interface.post',),
        ),
    ]
