# Generated by Django 2.1.3 on 2018-11-14 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver_interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpoolpost',
            name='passengers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
