# Generated by Django 2.1.1 on 2018-10-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_interface', '0002_carpoolpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
