# Generated by Django 2.1.1 on 2018-10-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_interface', '0003_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='city',
            new_name='departure_city',
        ),
        migrations.AddField(
            model_name='post',
            name='departure_state',
            field=models.CharField(choices=[('Alabama', 'AL'), ('Alaska', 'AK'), ('Arizona', 'AZ'), ('Arkansas', 'AR'), ('California', 'CA'), ('Colorado', 'CO'), ('Connecticut', 'CT'), ('Delaware', 'DE'), ('Florida', 'FL'), ('Georgia', 'GA'), ('Hawaii', 'HI'), ('Idaho', 'ID'), ('Illinois', 'IL'), ('Indiana', 'IN'), ('Iowa', 'IA'), ('Kansas', 'KS'), ('Kentucky', 'KY'), ('Louisiana', 'LA'), ('Maine', 'ME'), ('Maryland', 'MD'), ('Massachusetts', 'MA'), ('Michigan', 'MI'), ('Minnesota', 'MN'), ('Mississippi', 'MS'), ('Missouri', 'MO'), ('Montana', 'MT'), ('Nebraska', 'NE'), ('Nevada', 'NV'), ('New Hampshire', 'NH'), ('New Jersey', 'NJ'), ('New Mexico', 'NM'), ('New York', 'NY'), ('North Carolina', 'NC'), ('North Dakota', 'ND'), ('Ohio', 'OH'), ('Oklahoma', 'OK'), ('Oregon', 'OR'), ('Pennsylvania', 'PA'), ('Rhode Island', 'RI'), ('South Carolina', 'SC'), ('South Dakota', 'SD'), ('Tennessee', 'TN'), ('Texas', 'TX'), ('Utah', 'UT'), ('Vermont', 'VT'), ('Virginia', 'VA'), ('Washington', 'WA'), ('West Virginia', 'WV'), ('Wisconsin', 'WI'), ('Wyoming', 'WY'), ('American Samoa', 'AS'), ('District of Columbia', 'DC'), ('Federated States of Micronesia', 'FM'), ('Guam', 'GU'), ('Marshall Islands', 'MH'), ('Northern Mariana Islands', 'MP'), ('Palau', 'PW'), ('Puerto Rico', 'PR'), ('Virgin Islands', 'VI')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='destination_city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
