# Generated by Django 2.1.1 on 2018-10-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
