# Generated by Django 2.1.1 on 2018-10-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver_interface', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeedRidePost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='driver_interface.Post')),
                ('my_user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.MyUser')),
            ],
            bases=('driver_interface.post',),
        ),
    ]
