# Generated by Django 2.1.1 on 2018-12-10 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pssngr_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needridepost',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
